// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories.Context;

#nullable disable

namespace Repositories.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240521105624_migrationInit")]
    partial class migrationInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting",
                            Name = "Microwave oven",
                            Price = 10m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Contrary to popular belief, Lorem Ipsum is not simply random text.",
                            Name = "Sunglasses",
                            Price = 34m
                        },
                        new
                        {
                            Id = 3,
                            Description = "There are many variations of passages of Lorem Ipsum available",
                            Name = "Speaker",
                            Price = 78m
                        },
                        new
                        {
                            Id = 4,
                            Description = "The standard chunk of Lorem Ipsum used since the 1500s",
                            Name = "Watch",
                            Price = 188m
                        },
                        new
                        {
                            Id = 5,
                            Description = "in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
                            Name = "Laptop",
                            Price = 1340m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
